/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bgy_robot_accesscontrol_utils_TestNative */

#ifndef _Included_com_bgy_robot_accesscontrol_utils_TestNative
#define _Included_com_bgy_robot_accesscontrol_utils_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bgy_robot_accesscontrol_utils_TestNative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bgy_robot_accesscontrol_utils_TestNative_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
