server:
  tomcat:
    uri-encoding: UTF-8
  port: 8082
  servlet:
    context-path: /device
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/device?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 1
      min-idle: 1
      max-actice: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mvc:
    static-path-pattern: /static/**

restart:
  include:
    mapper: /mapper-[\\w-\\.]+jar
    pagehelper: /pagehelper-[\\w-\\.]+jar

mybatis:
  type-aliases-package: com.bgy.device.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.bgy.device.utils.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql